// Generated from Additional Additions 10.0.4+1.21.1 NeoForge jar lang data.
// Minecraft 1.21.1 NeoForge, mod version 10.0.4.
(() => {
    const rows = entries => entries.map(([id, name]) => ({ id: `additionaladditions:${id}`, name }));
    window.MOD_ID_PACKS.register({
        id: "additional_additions",
        name: "Additional Additions",
        category: "Utility and vanilla-plus",
        modIds: ["additionaladditions"],
        supportedVersions: ["1.21.1", "1.20.1"],
        source: "Generated from Modrinth version qpSDYH22 jar assets/additionaladditions/lang/en_us.json and META-INF/neoforge.mods.toml",
        modVersion: "10.0.4+1.21.1-neoforge",
        minecraftVersion: "1.21.1",
        loader: "NeoForge",
        verified: true,
        generatedAt: "2026-05-28",
        blocks: rows([
            ["rose_gold_block", "Rose Gold Block"],
            ["rope", "Rope"],
            ["glow_stick", "Glow Stick"],
            ["copper_patina", "Copper Patina"],
            ["patina_block", "Patina Block"],
            ["tinted_redstone_lamp", "Tinted Redstone Lamp"],
            ["cottonshiver", "Cottonshiver"],
            ["mudflower", "Mudflower"],
            ["crimson_blossom", "Crimson Blossom"],
            ["amber_blossom", "Amber Blossom"],
            ["bulbus", "Bulbus"],
            ["sawtooth_fern", "Sawtooth Fern"],
            ["frostleaf", "Frostleaf"],
            ["wisteria", "Wisteria"],
            ["spikeblossom", "Spikeblossom"],
            ["snapdragon", "Snapdragon"],
            ["lotus_lily", "Lotus Lily"]
        ]),
        items: rows([
            ["rose_gold_ingot", "Rose Gold Ingot"],
            ["rose_gold_sword", "Rose Gold Sword"],
            ["rose_gold_spear", "Rose Gold Spear"],
            ["rose_gold_axe", "Rose Gold Axe"],
            ["rose_gold_pickaxe", "Rose Gold Pickaxe"],
            ["rose_gold_shovel", "Rose Gold Shovel"],
            ["rose_gold_hoe", "Rose Gold Hoe"],
            ["rose_gold_helmet", "Rose Gold Helmet"],
            ["rose_gold_chestplate", "Rose Gold Chestplate"],
            ["rose_gold_leggings", "Rose Gold Leggings"],
            ["rose_gold_boots", "Rose Gold Boots"],
            ["rose_gold_horse_armor", "Rose Gold Horse Armor"],
            ["rose_gold_nautilus_armor", "Rose Gold Nautilus Armor"],
            ["berry_pie", "Sweet Berry Pie"],
            ["fried_egg", "Fried Egg"],
            ["honeyed_apple", "Honeyed Apple"],
            ["watering_can", "Watering Can"],
            ["wrench", "Wrench"],
            ["trident_shard", "Trident Shard"],
            ["glow_stick", "Glow Stick"],
            ["barometer", "Barometer"],
            ["mysterious_bundle", "Mysterious Bundle"],
            ["pocket_jukebox", "Pocket Jukebox"],
            ["chicken_nugget", "Chicken Nugget"],
            ["rope_arrow", "Rope Arrow"],
            ["music_disc_0308", "Music Disc"],
            ["music_disc_1007", "Music Disc"],
            ["music_disc_1507", "Music Disc"],
            ["white_suspicious_dye", "White Suspicious Dye"],
            ["brown_suspicious_dye", "Brown Suspicious Dye"],
            ["red_suspicious_dye", "Red Suspicious Dye"],
            ["orange_suspicious_dye", "Orange Suspicious Dye"],
            ["yellow_suspicious_dye", "Yellow Suspicious Dye"],
            ["lime_suspicious_dye", "Lime Suspicious Dye"],
            ["green_suspicious_dye", "Green Suspicious Dye"],
            ["cyan_suspicious_dye", "Cyan Suspicious Dye"],
            ["light_blue_suspicious_dye", "Light Blue Suspicious Dye"],
            ["blue_suspicious_dye", "Blue Suspicious Dye"],
            ["purple_suspicious_dye", "Purple Suspicious Dye"],
            ["magenta_suspicious_dye", "Magenta Suspicious Dye"],
            ["pink_suspicious_dye", "Pink Suspicious Dye"],
            ["cottonshiver_pod", "Cottonshiver Pod"],
            ["mudflower_seeds", "Mudflower Seeds"],
            ["crimson_blossom_seeds", "Crimson Blossom Seeds"],
            ["amber_blossom_seeds", "Amber Blossom Seeds"],
            ["bulbus_pod", "Bulbus Pod"],
            ["sawtooth_fern_fiddlehead", "Sawtooth Fern Fiddlehead"],
            ["frostleaf_pod", "Frostleaf Pod"],
            ["wisteria_vines", "Wisteria Vines"],
            ["spikeblossom_seeds", "Spikeblossom Seeds"],
            ["snapdragon_pod", "Snapdragon Pod"],
            ["lotus_lily_pod", "Lotus Lily Pod"],
            ["album", "Album"],
            ["white_album", "White Album"],
            ["light_gray_album", "Light Gray Album"],
            ["gray_album", "Gray Album"],
            ["black_album", "Black Album"],
            ["brown_album", "Brown Album"],
            ["red_album", "Red Album"],
            ["orange_album", "Orange Album"],
            ["yellow_album", "Yellow Album"],
            ["lime_album", "Lime Album"],
            ["green_album", "Green Album"],
            ["cyan_album", "Cyan Album"],
            ["light_blue_album", "Light Blue Album"],
            ["blue_album", "Blue Album"],
            ["purple_album", "Purple Album"],
            ["magenta_album", "Magenta Album"],
            ["pink_album", "Pink Album"]
        ]),
        entities: rows([
            ["glow_stick", "Glow Stick"]
        ])
    });
})();
