// Generated from Better Archeology 1.21.1-1.3.4 NeoForge jar assets.
// Minecraft 1.21.1 NeoForge, mod version 1.21.1-1.3.4.
(() => {
    const rows = entries => entries.map(([id, name]) => ({ id: `betterarcheology:${id}`, name }));
    window.MOD_ID_PACKS.register({
        id: "better_archeology",
        name: "Better Archeology",
        category: "Adventure and exploration",
        modIds: ["betterarcheology"],
        supportedVersions: ["1.21.1", "1.20.1"],
        source: "Generated from Modrinth version rp4lPDKI jar assets/betterarcheology/lang/en_us.json, blockstates, item models, assets/betterarcheology/sounds.json, and META-INF/neoforge.mods.toml",
        modVersion: "1.21.1-1.3.4",
        minecraftVersion: "1.21.1",
        loader: "NeoForge",
        verified: true,
        generatedAt: "2026-05-28",
        blocks: rows([
            ["archeology_table", "Archeology Table"],
            ["chicken_fossil", "Chicken-Fossil"],
            ["chicken_fossil_body", "Chicken-Fossil Body"],
            ["chicken_fossil_head", "Chicken-Fossil Skull"],
            ["chiseled_bone_block", "Chiseled Bone Block"],
            ["cracked_mud_brick_slab", "Cracked Mud Brick Slab"],
            ["cracked_mud_brick_stairs", "Cracked Mud Brick Stairs"],
            ["cracked_mud_bricks", "Cracked Mud Bricks"],
            ["creeper_fossil", "Creeper-Fossil"],
            ["creeper_fossil_body", "Creeper-Fossil Body"],
            ["creeper_fossil_head", "Creeper-Fossil Skull"],
            ["evoker_trap", "Evoker Trap"],
            ["fossiliferous_dirt", "Fossiliferous Dirt"],
            ["growth_totem", "Totem of Growth"],
            ["guardian_fossil", "Guardian-Fossil"],
            ["guardian_fossil_body", "Guardian-Fossil Body"],
            ["guardian_fossil_head", "Guardian-Fossil Skull"],
            ["infested_mud_bricks", "Infested Mud Bricks"],
            ["loot_vase", "Ancient Vase"],
            ["loot_vase_creeper", "Ancient Vase"],
            ["loot_vase_green", "Ancient Vase"],
            ["ocelot_fossil", "Ocelot-Fossil"],
            ["ocelot_fossil_body", "Ocelot-Fossil Body"],
            ["ocelot_fossil_head", "Ocelot-Fossil Skull"],
            ["radiance_totem", "Totem of Radiance"],
            ["rotten_door", "Rotten Door"],
            ["rotten_fence", "Rotten Fence"],
            ["rotten_fence_gate", "Rotten Fence Gate"],
            ["rotten_log", "Rotten Log"],
            ["rotten_planks", "Rotten Planks"],
            ["rotten_pressure_plate", "Rotten Pressure Plate"],
            ["rotten_slab", "Rotten Slab"],
            ["rotten_stairs", "Rotten Stairs"],
            ["rotten_trapdoor", "Rotten Trapdoor"],
            ["sheep_fossil", "Sheep-Fossil"],
            ["sheep_fossil_body", "Sheep-Fossil Body"],
            ["sheep_fossil_head", "Sheep-Fossil Skull"],
            ["suspicious_dirt", "Suspicious Dirt"],
            ["suspicious_red_sand", "Suspicious Red Sand"],
            ["vase", "Ancient Vase"],
            ["vase_creeper", "Ancient Vase"],
            ["vase_green", "Ancient Vase"],
            ["villager_fossil", "Villager-Fossil"],
            ["villager_fossil_body", "Villager-Fossil Body"],
            ["villager_fossil_head", "Villager-Fossil Skull"],
            ["wolf_fossil", "Wolf-Fossil"],
            ["wolf_fossil_body", "Wolf-Fossil Body"],
            ["wolf_fossil_head", "Wolf-Fossil Skull"]
        ]),
        items: rows([
            ["archeology_table", "Archeology Table"],
            ["artifact_shards", "Artifact Shards"],
            ["bomb", "Rusty Bomb"],
            ["chicken_fossil", "Chicken-Fossil"],
            ["chicken_fossil_body", "Chicken-Fossil Body"],
            ["chicken_fossil_head", "Chicken-Fossil Skull"],
            ["chiseled_bone_block", "Chiseled Bone Block"],
            ["cracked_mud_brick_slab", "Cracked Mud Brick Slab"],
            ["cracked_mud_brick_stairs", "Cracked Mud Brick Stairs"],
            ["cracked_mud_bricks", "Cracked Mud Bricks"],
            ["creeper_fossil", "Creeper-Fossil"],
            ["creeper_fossil_body", "Creeper-Fossil Body"],
            ["creeper_fossil_head", "Creeper-Fossil Skull"],
            ["diamond_brush", "Diamond Brush"],
            ["evoker_trap", "Evoker Trap"],
            ["fossiliferous_dirt", "Fossiliferous Dirt"],
            ["growth_totem", "Totem of Growth"],
            ["guardian_fossil", "Guardian-Fossil"],
            ["guardian_fossil_body", "Guardian-Fossil Body"],
            ["guardian_fossil_head", "Guardian-Fossil Skull"],
            ["infested_mud_bricks", "Infested Mud Bricks"],
            ["iron_brush", "Iron Brush"],
            ["loot_vase", "Ancient Vase"],
            ["loot_vase_creeper", "Ancient Vase"],
            ["loot_vase_green", "Ancient Vase"],
            ["music_disc_swings", "Music Disc"],
            ["netherite_brush", "Netherite Brush"],
            ["ocelot_fossil", "Ocelot-Fossil"],
            ["ocelot_fossil_body", "Ocelot-Fossil Body"],
            ["ocelot_fossil_head", "Ocelot-Fossil Skull"],
            ["radiance_totem", "Totem of Radiance"],
            ["rotten_door", "Rotten Door"],
            ["rotten_fence", "Rotten Fence"],
            ["rotten_fence_gate", "Rotten Fence Gate"],
            ["rotten_log", "Rotten Log"],
            ["rotten_planks", "Rotten Planks"],
            ["rotten_pressure_plate", "Rotten Pressure Plate"],
            ["rotten_slab", "Rotten Slab"],
            ["rotten_stairs", "Rotten Stairs"],
            ["rotten_trapdoor", "Rotten Trapdoor"],
            ["sheep_fossil", "Sheep-Fossil"],
            ["sheep_fossil_body", "Sheep-Fossil Body"],
            ["sheep_fossil_head", "Sheep-Fossil Skull"],
            ["soul_totem", "Totem of Souls"],
            ["suspicious_dirt", "Suspicious Dirt"],
            ["suspicious_red_sand", "Suspicious Red Sand"],
            ["torrent_totem", "Totem of Torrents"],
            ["unidentified_artifact", "Unidentified Artifact"],
            ["vase", "Ancient Vase"],
            ["vase_creeper", "Ancient Vase"],
            ["vase_green", "Ancient Vase"],
            ["villager_fossil", "Villager-Fossil"],
            ["villager_fossil_body", "Villager-Fossil Body"],
            ["villager_fossil_head", "Villager-Fossil Skull"],
            ["wolf_fossil", "Wolf-Fossil"],
            ["wolf_fossil_body", "Wolf-Fossil Body"],
            ["wolf_fossil_head", "Wolf-Fossil Skull"]
        ]),
        sounds: rows([
            ["swings", "Swings"]
        ])
    });
})();
