// Generated from Ecologics 2.3.6 NeoForge jar lang and sound data.
// Minecraft 1.21.1 NeoForge, mod version 2.3.6.
(() => {
    const rows = entries => entries.map(([id, name]) => ({ id: `ecologics:${id}`, name }));
    window.MOD_ID_PACKS.register({
        id: "ecologics",
        name: "Ecologics",
        category: "Worldgen and biomes",
        modIds: ["ecologics"],
        supportedVersions: ["1.21.1", "1.20.1"],
        source: "Generated from Modrinth version ml3dpcRE jar assets/ecologics/lang/en_us.json, assets/ecologics/sounds.json, and META-INF/neoforge.mods.toml",
        modVersion: "2.3.6-NeoForge",
        minecraftVersion: "1.21.1",
        loader: "NeoForge",
        verified: true,
        generatedAt: "2026-05-28",
        blocks: rows([
            ["coconut", "Coconut"],
            ["hanging_coconut", "Hanging Coconut"],
            ["coconut_button", "Coconut Button"],
            ["coconut_door", "Coconut Door"],
            ["coconut_fence", "Coconut Fence"],
            ["coconut_fence_gate", "Coconut Fence Gate"],
            ["coconut_seedling", "Coconut Seedling"],
            ["coconut_leaves", "Coconut Leaves"],
            ["coconut_log", "Coconut Log"],
            ["coconut_planks", "Coconut Planks"],
            ["coconut_pressure_plate", "Coconut Pressure Plate"],
            ["coconut_slab", "Coconut Slab"],
            ["coconut_stairs", "Coconut Stairs"],
            ["coconut_trapdoor", "Coconut Trapdoor"],
            ["coconut_wood", "Coconut Wood"],
            ["seashell", "Seashell"],
            ["seashell_block", "Seashell Block"],
            ["seashell_tile_slab", "Seashell Tile Slab"],
            ["seashell_tile_stairs", "Seashell Tile Stairs"],
            ["seashell_tile_wall", "Seashell Tile Wall"],
            ["seashell_tiles", "Seashell Tiles"],
            ["sandcastle", "Sandcastle"],
            ["stripped_coconut_log", "Stripped Coconut Log"],
            ["stripped_coconut_wood", "Stripped Coconut Wood"],
            ["coconut_sign", "Coconut Sign"],
            ["coconut_wall_sign", "Coconut Wall Sign"],
            ["coconut_hanging_sign", "Coconut Hanging Sign"],
            ["coconut_wall_hanging_sign", "Coconut Wall Hanging Sign"],
            ["prickly_pear", "Prickly Pear"],
            ["snow_brick_slab", "Snow Brick Slab"],
            ["snow_brick_stairs", "Snow Brick Stairs"],
            ["snow_brick_wall", "Snow Brick Wall"],
            ["snow_bricks", "Snow Bricks"],
            ["ice_brick_slab", "Ice Brick Slab"],
            ["ice_brick_stairs", "Ice Brick Stairs"],
            ["ice_brick_wall", "Ice Brick Wall"],
            ["ice_bricks", "Ice Bricks"],
            ["pot", "Carved Pot"],
            ["thin_ice", "Thin Ice"],
            ["walnut_button", "Walnut Button"],
            ["walnut_door", "Walnut Door"],
            ["walnut_fence", "Walnut Fence"],
            ["walnut_fence_gate", "Walnut Fence Gate"],
            ["walnut_leaves", "Walnut Leaves"],
            ["walnut_log", "Walnut Log"],
            ["walnut_planks", "Walnut Planks"],
            ["walnut_pressure_plate", "Walnut Pressure Plate"],
            ["walnut_slab", "Walnut Slab"],
            ["walnut_stairs", "Walnut Stairs"],
            ["walnut_trapdoor", "Walnut Trapdoor"],
            ["walnut_wood", "Walnut Wood"],
            ["stripped_walnut_log", "Stripped Walnut Log"],
            ["stripped_walnut_wood", "Stripped Walnut Wood"],
            ["walnut_sign", "Walnut Sign"],
            ["walnut_wall_sign", "Walnut Wall Sign"],
            ["walnut_hanging_sign", "Walnut Hanging Sign"],
            ["walnut_wall_hanging_sign", "Walnut Wall Hanging Sign"],
            ["walnut_sapling", "Walnut Sapling"],
            ["azalea_button", "Azalea Button"],
            ["azalea_door", "Azalea Door"],
            ["azalea_fence", "Azalea Fence"],
            ["azalea_fence_gate", "Azalea Fence Gate"],
            ["azalea_flower", "Azalea Flower"],
            ["azalea_log", "Azalea Log"],
            ["azalea_planks", "Azalea Planks"],
            ["azalea_pressure_plate", "Azalea Pressure Plate"],
            ["azalea_slab", "Azalea Slab"],
            ["azalea_stairs", "Azalea Stairs"],
            ["azalea_trapdoor", "Azalea Trapdoor"],
            ["azalea_wood", "Azalea Wood"],
            ["flowering_azalea_door", "Flowering Azalea Door"],
            ["flowering_azalea_fence", "Flowering Azalea Fence"],
            ["flowering_azalea_fence_gate", "Flowering Azalea Fence Gate"],
            ["flowering_azalea_log", "Flowering Azalea Log"],
            ["flowering_azalea_planks", "Flowering Azalea Planks"],
            ["flowering_azalea_slab", "Flowering Azalea Slab"],
            ["flowering_azalea_stairs", "Flowering Azalea Stairs"],
            ["flowering_azalea_trapdoor", "Flowering Azalea Trapdoor"],
            ["flowering_azalea_wood", "Flowering Azalea Wood"],
            ["surface_moss", "Surface Moss"],
            ["moss_layer", "Moss Layer"],
            ["stripped_azalea_log", "Stripped Azalea Log"],
            ["stripped_azalea_wood", "Stripped Azalea Wood"],
            ["azalea_sign", "Azalea Sign"],
            ["azalea_wall_sign", "Azalea Wall Sign"],
            ["azalea_hanging_sign", "Azalea Hanging Sign"],
            ["azalea_wall_hanging_sign", "Azalea Wall Hanging Sign"],
            ["flowering_azalea_sign", "Flowering Azalea Sign"],
            ["flowering_azalea_wall_sign", "Flowering Azalea Wall Sign"],
            ["flowering_azalea_hanging_sign", "Flowering Azalea Hanging Sign"],
            ["flowering_azalea_wall_hanging_sign", "Flowering Azalea Wall Hanging Sign"],
            ["potted_walnut_sapling", "Potted Walnut Sapling"],
            ["potted_coconut_seedling", "Potted Coconut Seedling"],
            ["potted_azalea_flower", "Potted Azalea Flower"]
        ]),
        items: rows([
            ["coconut_crab_spawn_egg", "Coconut Crab Spawn Egg"],
            ["camel_spawn_egg", "Camel Spawn Egg"],
            ["penguin_spawn_egg", "Penguin Spawn Egg"],
            ["squirrel_spawn_egg", "Squirrel Spawn Egg"],
            ["coconut_slice", "Coconut Slice"],
            ["coconut_husk", "Coconut Husk"],
            ["crab_claw", "Crab Claw"],
            ["crab_meat", "Crab Meat"],
            ["tropical_stew", "Tropical Stew"],
            ["music_disc_coconut", "Music Disc"],
            ["coconut_boat", "Coconut Boat"],
            ["walnut_boat", "Walnut Boat"],
            ["azalea_boat", "Azalea Boat"],
            ["flowering_azalea_boat", "Flowering Azalea Boat"],
            ["coconut_chest_boat", "Coconut Boat with Chest"],
            ["walnut_chest_boat", "Walnut Boat with Chest"],
            ["azalea_chest_boat", "Azalea Boat with Chest"],
            ["flowering_azalea_chest_boat", "Flowering Azalea Boat with Chest"],
            ["prickly_pear", "Prickly Pear"],
            ["cooked_prickly_pear", "Cooked Prickly Pear"],
            ["penguin_feather", "Penguin Feather"],
            ["walnut", "Walnut"]
        ]),
        entities: rows([
            ["coconut_crab", "Coconut Crab"],
            ["camel", "Camel"],
            ["penguin", "Penguin"],
            ["squirrel", "Squirrel"],
            ["boat", "Boat"],
            ["chest_boat", "Boat with Chest"]
        ]),
        sounds: rows([
            ["block.coconut.smash", "Block Coconut Smash"],
            ["entity.coconut_crab.ambient", "Coconut Crab Ambient"],
            ["entity.coconut_crab.death", "Coconut Crab Death"],
            ["entity.coconut_crab.hurt", "Coconut Crab Hurt"],
            ["entity.penguin.ambient", "Penguin Ambient"],
            ["entity.penguin.death", "Penguin Death"],
            ["entity.penguin.hurt", "Penguin Hurt"],
            ["entity.squirrel.ambient", "Squirrel Ambient"],
            ["entity.squirrel.death", "Squirrel Death"],
            ["entity.squirrel.hurt", "Squirrel Hurt"],
            ["music_disc.coconut", "Music Disc Coconut"],
            ["block.thin_ice.crack", "Thin Ice Crack"],
            ["entity.camel.ambient", "Camel Ambient"],
            ["entity.camel.death", "Camel Death"],
            ["entity.camel.hurt", "Camel Hurt"],
            ["entity.camel.angry", "Camel Angry"],
            ["entity.camel.eat", "Camel Eat"],
            ["entity.camel.step", "Camel Step"],
            ["entity.camel.chest", "Camel Chest"]
        ])
    });
})();
